### ISSUE TITLE
New operator request to add documents to WEX Content Analytics collections

### ISSUE THREAD

**Issue by mgorbat** [IBMStreams/streamsx.watsonexplorer#15]
WEX-CA has a RestAPI to add documents to a collection.
IBM Streams should be able to post a document into WEX CA using this API and write document metadata as fields.
This would allow to analyze the text using Content Miner tool of the WEX-CA and explore it using facets generated from the metadata.
Streams developer should be able to map tuple attributes on API fields that will be turned into "facets".

**Comment by cancilla** [comment]
I have reviewed the Admin API and this appears to be straight-forward to implement. The only difficult part is how to do the mapping from tuple attributes to facets. The cleanest approach would have been to allow the user to specify a map as a parameter value. Unfortunately, Java operators do not support passing in maps as parameter values so a different solution will need to be used. 

Here are some possible solutions that could be implemented:

### Solution 1 - List of attributes
In this solution, the operator would have a parameter that accepts a list of Tuple Attributes. The name of the tuple attribute would be taken as the facet name. 

For example, assume the following operator definition: 

```
My_Input_Stream = tuple<rstring docId, rstring docText, rstring firstname, rstring lastname>
...
() as AddDocOp = PushDocument(My_Input_Stream) {
  param
    facetAttributeList: firstname, lastname
}
```

Here, the operator is receiving a tuple with type `My_Input_Stream`. The parameter `facetAttributeList` specifies that attributes `firstname` and `lastname` should be mapped to facets. In this solution, the value of `firstname` and `lastname` would be mapped to facets called "firstname" and "lastname".

**PRO:** It is fairly easy for the user to specify which attributes to map to facets.
**CON:** This approach prevents the same attribute from being mapped to multiple facets. It also requires that the names of the attributes in the input schema must match the facet names in the WEX collection. This may require an upstream `Functor` to modify the input schema. This approach also prevents the user from hard-coding a facet to a string unless that string is passed in as an attribute. 

### Solution 2 - Mapping attribute
In this solution, the user would need to create the mapping themselves in an upstream operator and pass that map in as an attribute. This doesn't really satisfy the requirement of having the operator do the mapping itself, but it's worth exploring since it gives the user fully control over how the mapping is done. 

For this to work, the user would likely need a `Custom` or `Functor` upstream where they would create an `rstring` value with this format: `{"facetname" : "facetvalue"}`. Psuedo-code in a `Custom` operator may look like this: 

```
(Output_Stream) = Custom(Input_Stream) {
  logic
    onTuple Input_Stream:
    {
      mutable map<rstring, rstring> my_map = {};
      insertM(my_map, "facet1", Input_Stream.attr1);
      insertM(my_map, "facet2", Input_Stream.attr2);
      
      submit({facets=(rstring)my_map, ...}, OutputStream));
    }
}
```

**PRO:** Gives the user full control over how the mapping is done.
**CON:** Not handled automatically by the operator. Requires the user to have an additional operator upstream in order to build this mapping. 

### Solution 3 - Hybrid
This solution would actually implement both **Solution 1** and **Solution 2**. For simple scenarios where there is a direct mapping between attribute name and facet, the user can simply specify the attribute names in a parameter. Where the user needs more control over how attributes are mapped to facets, the operator can accept the full mapping as a single attribute. 

**PRO:** Doesn't introduce any restrictions and makes the mapping easy to do for simple cases. For complex cases, the user has full control over how that mapping is done. 
**CON:** May make the operator confusing to use, although this can be mitigated with good docs and examples. 

I am leaning towards **Solution 3**, however I would like to hear any feedback or other solutions.

**Comment by chanskw** [comment]
What about a slightly modified solution (3)?

We will provide an operator that supports the facetAttributeList parameter.  The operator will also support Solution(2) where we accept the map from the input stream.  In addition, we provide a composite that takes a map as a parameter.  The composite handles the mapping, creating the necessary functor / custom operators.  

End user can use the operator as is.. using the facetAttributeList, or they can use the composite if they need more advanced mapping?

**Comment by mgorbat** [comment]
From the implementation perspective, the most frequent scenario will be following the pattern described in Solution 1, i.e. selecting a list of attributes that should be added as facets, not changing any attribute names, mapping each selected attribute to only one facet. There are many other aspects of data preparation that take place before writing into Content Analytics, and, in my opinion, they all should be upstream and outside of the toolkit.
The WEX CA product also allows to add a descriptive name for the facet, so not being able to change names in the operator will not affect the user experience.
My vote is for Solution 1 in its simplest and most restricted form until any users ask for enhancements.

**Comment by mgorbat** [comment]
Also, which WEX-AC API 2.0 method are we implementing?
I have found two possible methods in the documentation:
/collections/indexer/document/add/file - Add a document with binary content
/collections/indexer/document/add/text - Add a document with text content
Not sure if I understand the difference and which one would provide a more generic approach and is recommended.

**Comment by cancilla** [comment]
@mgorbat The `/file` API appears to be used for uploading an actual file from disk to the collection, whereas `/text` is for uploading just the textual content. I think both use cases are important, but I will start with implementing `/text` and then circle back around to do `/file`.

**Comment by cancilla** [comment]
I appreciate the feedback with regards to mapping. I have decided that the initial version of this toolkit will support **Solution 1**. The primary reason for supporting this solution is that I have realized that this mapping is not actually mapping from attribute to *facet*, but rather mapping from attribute to *index field*. The difference is that index fields in a WEX collection map to a facet, and there can be many-to-one and many-to-many relationship between index fields and facets. Also, in thinking about this more,  it is really the responsibility of the WEX admin to create index fields that map to the documents being added, and not the other way around. 

That being said, if there is ever an actual use case presented where **Solution 1** will not work, implementing **Solution 3** (along with @chanskw's suggestion) will still be possible. 

I have created a draft design doc for the new operator: [(DRAFT) PushText Operator Design](https://github.com/IBMStreams/streamsx.watsonexplorer/wiki/(DRAFT)-PushText-Operator-Design)

@mgorbat, @chanskw ... please review and let me know if there are any concerns.

**Comment by markheger** [comment]
close since no demand for this
